version: "3.9"

services:
  app:
    build: .
    command: "python manage.py runserver --host 0.0.0.0 --port 8000"
    ports:
      - "8888:8000"
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5444:5432"
  
  redis:
    image: redis:latest
    ports:
      - "6333:6379"
  
  celery:
    build: .
    command: "celery -A config worker --loglevel=info"
    depends_on:
      - redis
      - postgres
      - app
